#!/usr/bin/env python3
# Check if hostname belongs to network
# Usage: network_includes_host network hostname
# Example: network_includes_host 172.16.0.0/16 172.16.0.1
#          network_includes_host 10.0.0.0/24 dns.of.host 
# Exit codes: 0 - true, 1 - false
import ipaddress
import socket
import sys
exit(
    int(
        not ipaddress.ip_address(socket.gethostbyname(sys.argv[2]))
            in ipaddress.ip_network(sys.argv[1])
    )
)
